name: Engineering Portfolio | Joseph Mei
title: Engineering Portfolio | Joseph Mei
description: Engineering Portfolio of Joseph Mei, showcasing various projects and technical skills.
tags:
  - Portfolio
  - Engineering
  - MIT
  - Joseph Mei
  - Projects
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Resume
    url: /Resume
  - title: Contact
    url: /contact
email: jmei0311@mit.edu
# See: https://disqus.com/
disqus_username: N/A
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: N/A
